name = "GeneralizedGenerated"
uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
authors = ["thautwarm"]
version = "0.1.2"

[deps]
CanonicalTraits = "a603d957-0e48-4f86-8fbd-0b7bc66df689"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
JuliaVariables = "b14d175d-62b4-44ba-8fb7-3064adc8c3ec"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
NameResolution = "71a1bf82-56d0-4bbc-8a3c-48b961074391"

[compat]
julia = "1"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "BenchmarkTools"]
